# Generated by Django 5.1.7 on 2025-03-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('idtipo_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_unidad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_unidad',
            },
        ),
    ]
