# Generated by Django 5.1.7 on 2025-03-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('idindicador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_indicador', models.CharField(max_length=45)),
                ('peso_indicador', models.IntegerField()),
                ('tipo_indicador', models.CharField(max_length=45)),
                ('idpilar', models.ForeignKey(db_column='idpilar', on_delete=django.db.models.deletion.CASCADE, to='core.pilar')),
            ],
            options={
                'db_table': 'indicador',
            },
        ),
    ]
