# Generated by Django 5.1.7 on 2025-03-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True, serialize=False)),
                ('idindicador', models.ForeignKey(db_column='idindicador', on_delete=django.db.models.deletion.CASCADE, to='core.indicador')),
                ('idunidad_analisis', models.ForeignKey(db_column='idunidad_analisis', on_delete=django.db.models.deletion.CASCADE, to='core.unidadanalisis')),
            ],
            options={
                'db_table': 'registro',
            },
        ),
    ]
