# Generated by Django 5.1.7 on 2025-03-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_valorcualitativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorCuantitativo',
            fields=[
                ('idregistro', models.OneToOneField(db_column='idregistro', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.registro')),
                ('valor_cuantitativo', models.FloatField()),
            ],
            options={
                'db_table': 'valor_cuantitativo',
            },
        ),
    ]
