# Generated by Django 5.1.7 on 2025-03-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_valorcuantitativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceIndicador',
            fields=[
                ('idindice_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ii', models.DateField(auto_now_add=True, serialize=False)),
                ('valor_ii', models.FloatField(blank=True, null=True)),
                ('clasificacion_ii', models.CharField(blank=True, max_length=45, null=True)),
                ('idindicador', models.ForeignKey(blank=True, db_column='idindicador', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indicador')),
                ('idunidad_analisis', models.ForeignKey(blank=True, db_column='idunidad_analisis', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registro')),
            ],
            options={
                'db_table': 'indice_indicador',
            },
        ),
    ]
