# Generated by Django 5.1.7 on 2025-03-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_indiceindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicePilar',
            fields=[
                ('idindice_pilar', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ip', models.DateField(auto_now_add=True, serialize=False)),
                ('valor_ip', models.FloatField(blank=True, null=True)),
                ('clasificacion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('idpilar', models.ForeignKey(blank=True, db_column='idpilar', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indicador')),
                ('idunidad_analisis', models.ForeignKey(blank=True, db_column='idunidad_analisis', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indiceindicador')),
            ],
            options={
                'db_table': 'indice_pilar',
            },
        ),
    ]
