# Generated by Django 5.1.7 on 2025-03-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_indicepilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceGeneral',
            fields=[
                ('idindice_general', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ig', models.DateField(auto_now_add=True, serialize=False)),
                ('valor_ig', models.FloatField(blank=True, null=True)),
                ('clasificacion_ig', models.CharField(blank=True, max_length=45, null=True)),
                ('idunidad_analisis', models.ForeignKey(blank=True, db_column='idunidad_analisis', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indicepilar')),
            ],
            options={
                'db_table': 'indice_general',
            },
        ),
    ]
